version: '3.8'

services:
  vision-mcp-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
    volumes:
      - ./images:/app/images
    env_file:
      - .env